config/routes.rb
Rails.application.routes.draw do
# get 'sessions/new'  # pode tirar esse get
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm

  root to: "static_pages#index"  # colocar o nome do controller # nome do método

  # para visuzlizar as rotas disponíveis na aplicação : rails routes

  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'  # ele vai pegar o método contato e mandar pro arquivo contato que está dentro da pasta static_pages
  get 'novo_contato', to: 'static_pages#novo_contato'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  # para visuzlizar as rotas disponíveis na aplicação : rails routes


  # permite que você rapidamente declare todas as rotas comuns para um controller.
  # uma chamada única para resources pode declarar todas as rotas necessárias para as actions index, show, new, edit, create, update e destroy.
  resources :contacts
  resources :users, only: [:new, :create, :show, :edit, :update]  # como é a rota de cadastro, só pode ter acesso à rota new e create - e pra mostrar = :show
  # não tem a rota de destroy pois não fiz pra deletar usuário
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

    # validações dos atributos do contato
    validates :name, presence: true, length: { maximum: 50 }
    validates :phone, presence: true

    
    # a classe contato pertence ao user. logo, todo contato tem que ter um usuário.
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password  # reforçar a segurança, vai criar um hash da senha

    # algumas validações

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    # pra ver se o email é válido ou não


    validates :name, presence: true, length: { maximum: 50 }  # o usuário não pode passar sem adicionar um nome
    validates :password, length: { minimum: 6 }
    validates :email, presence: true, length: { maximum: 255 },
                                      format: { with: VALID_EMAIL_REGEX },
                                      uniqueness: { case_sensitive: true }  # verificar se a string está em caixa alta ou cx baixa
                                      
    
                                      
    # a classe usuário TEM MUITOS CONTATOSSSS
    has_many :contacts  # observe que essa classe vem no plural
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    include SessionsHelper

    private

    def require_logged_in_user
        unless user_signed_in?  # a não ser que ele esteja logado, redirecione
            flash[:danger] = 'Área restrita. Por favor, realize o login.'  # se não estiver logado, não consegue acessar a página de contato
            redirect_to entrar_path
        end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # essas actions acontecem por ordem 
  before_action :require_logged_in_user
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = current_user.contacts  # contatos APENAS do usuário x
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: "O contato foi criado!" }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: "O contato foi atualizado." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "O contato foi deletado!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/sessions_controller.rb
# esse controller foi criado com rails g controller sessions new create

class SessionsController < ApplicationController

  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create
      user = User.find_by(email: params[:session][:email].downcase)  # procurar o usuário no banco
      if user && user.authenticate(params[:session][:password])
        sign_in(user)
        redirect_to contacts_path
      else
        flash.now[:danger] = 'Email ou senha inválidos'
        render 'new'

      end
  end


  def destroy
    sign_out
    flash[:success] = 'Logout com sucesso'
    redirect_to entrar_path
  end	

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index
        @nome = "Heloísa"
    end

    def sobre 
    end

    def contato 
    end
    
    def novo_contato
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_in_user, only: [:edit, :update]
    def new  # vai mostrar o formulário de cadastro
        @user = User.new
    end

    def create # vai receber o post pra fazer a criação dessa rota
        @user = User.new(user_params)  # 
        if @user.save
            flash[:success] = 'Usuário cadastrado com sucesso'
            redirect_to root_url
        else
            render 'new'
        end           
    end

    def edit
    
    end

    def update
        if current_user.update(user_params)
            flash[:success] = 'Dados atualizados'
            redirect_to contacts_url
        else
            render 'edit'
        end
    end


    private

    def user_params
        params.require(:user).permit(:email, :name, :password, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end 


    def sign_out
        session.delete(:user_id)
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
        # se essa variável já foi setada, não vai criar um novo no banco
    end

    def user_signed_in?
        !current_user.nil?
        # para saber se o usuário está logado ou não
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= render 'layouts/error_messages', object: f.object %>

<!--
  esse f - (f.object, f.label = vem da variável criada no for do new/edit)
-->

<div class="form-group">
  <%=f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%=f.label :phone %>
  <%= f.text_field :phone, class: 'form-control' %>
</div>

app/views/contacts/edit.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>Editar contato</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 col-xs-12">
        <%= form_for @contact do |f| %>
            <%= render 'form', f: f %>

            <%= f.submit 'Atuallizar', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <h1>Meus contatos</h1>
    <h2>Olá, <%= current_user.name %>!</h2>
  </div>

  <div class="col-md-8 col-md-offset-2 col-xs-12">
    <table class="table table-striped">
      <thead>

        <tr>
          <th>Nome</th>
          <th>Telefone</th>
          <th colspan="2" style="text-align: right; padding-right: 0">
            <%= link_to 'Novo Contato', new_contact_path, class: 'btn btn-success' %>
          </th>
        <tr>

      </thead>

      <tbody>

        <% if @contacts.empty? %>
          <tr>
            <td colspan="4" class="text-center">
              <h3>Sem contatos cadastrados</h3>
              <%= link_to 'Clique aqui', new_contact_path %> para adicionar um novo contato
            </td>
          </tr>
        <% end %>

        <% @contacts.each do |contato| %>
          <tr>
            <td>
              <%= contato.name %>
            </td>

            <td>
              <%= contato.phone %>
            </td>

            <td>
              <%= link_to 'Editar', edit_contact_path(contato), class: 'btn btn-warning' %>
            </td>

            <td>
              <%= link_to 'Excluir', contact_path(contato), method: :delete, class: 'btn btn-danger', data: { confirm: 'Tem certeza que deseja apagar este contato?' } %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>Adicionar novo contato</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 col-xs-12">
        <%= form_for @contact do |f| %>
            <%= render 'form', f: f %>

            <%= f.submit 'Salvar', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="">
        <div class="alert alert-danger">
            Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <small>
        <%= link_to 'Agendinha.  Todos os direitos reservados.', root_path %>
    </small>

    <nav>
        <ul>
            <li>
                <%= link_to 'Sobre', sobre_path %>  <!-- sempre lembrar de colocar o _path pois é um método do ruby que indica o caminho a seguir -->
                <!-- esse sobre vem da string sobre do get, no arquivo routes.rb -->
            </li>

            <li>
                <%= link_to 'Contato', contato_path %>
            </li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- Todo arquivo partial começa com um underscore -->

<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
      </button>
      <% if !user_signed_in? %>
        <%= link_to 'Agendinha', root_url, class: 'navbar-brand' %>
      <% else %>
        <%= link_to 'Agendinha', contacts_path, class: 'navbar-brand' %>
      <% end %>
    </div>

  <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
    <div class="collapse navbar-collapse" id="expanded-menu">
        <ul class="nav navbar-nav">
        <% if !user_signed_in? %>
            <li class="active">
                <%= link_to 'Nova conta', new_user_path %>
            </li>
        <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">

            <% if !user_signed_in? %>
              <li>
                <%= link_to 'Entrar', entrar_path %>  <!-- entrar_path pois foi criado uma rota chamada entrar no routes -->
              </li>
            <% else %>

            
            <%= link_to 'Editar', edit_user_path(current_user), class: 'navbar-brand' %>
            <%= link_to 'Sair', sair_path,  method: :delete, class: 'navbar-brand' %>
            

            <% end %>


        </ul>

    </div>

  </div>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agendinha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
    
      <!--
      sempre que tiver mensagens de flash, esse bloco abaixo vai ajudar bastante e no controller
      coloca a mensagem desejada. No caso do users_controller vai a mensagem de sucesso no método
      create >>> flash[:success]
      -->

      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        <% end %>
      <% end %>

      <!--
      <% if user_signed_in? %>
      

        <a href="#">
          <button type="button" class="btn"
            style="background-color: black; color: white; border-radius: 50px; padding: 5px 80px 5px 80px;">Editar</button>
        </a>

        
      <% end %>
      -->

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>

<p>
    Entre em contato com <a href="https://github.com/heloisaldanha">@heloisaldanha</a> para saber mais
</p>

app/views/static_pages/index.html.erb
<!--
<p>Olá, <%= @nome %> </p>   a marcação <%= %> só vale para variáveis. Estava tentando colocar Olá, Heloísa dentro e deu erro
-->

<div class="jumbotron">
    <h1>Agendinha</h1>
    <p>
        Gerencie seus contatos em qualquer lugar!
    </p>

    <p>
        <%= link_to 'Crie sua conta', new_user_path, class: 'btn btn-primary btn-lg' %>
    </p>
</div>

app/views/static_pages/novo_contato.html.erb
<h1>Novo Contato</h1>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>

<p>
    Criado com o intuito de aprender um pouco mais sobre o Framework Ruby on Rails
</p>

app/views/users/_form.html.erb
<%= render 'layouts/error_messages', object: f.object %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

app/views/users/edit.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>Editar dados</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 col-xs-12">

        <%= form_for current_user do |f| %>

            <%= render 'form', f: f %>

        <%= f.submit 'Salvar', class: 'btn btn-primary' %>

        <% end %>

    </div>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>Cadastre-se</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 col-xs-12">

        <%= form_for @user do |f| %>

            <%= render 'form', f: f %>

        <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>

        <% end %>

    </div>
</div>

app/views/users/show.html.erb
<h1>Olá, <%= current_user.name %>!</h1>